### ISSUE TITLE
Error: Cannot find module 'cdif-util'

### ISSUE THREAD

**Issue by vcka** [out4b/cdif-onvif-manager#1]
On starting got this error

**Comment by plandevida** [comment]
same error, this library isn't already on node registry

**Comment by out4b** [comment]
Sorry the README was not clear on this. 

You may need to assign NODE_PATH=<cdif-install-dir>/lib environment variable before launch cdif

**Comment by plandevida** [comment]
Same error. And cdif-device neither is not found.

**Comment by out4b** [comment]
This module can be loaded only by cdif: https://github.com/out4b/cdif.git

Please clone above cdif repo and do npm install inside cdif/ folder. Then in cdif/ folder you may start cdif with npm start command which set NODE_PATH env variable. You may modify cdif/modules.json file to customize the list of supported modules to be loaded by cdif. And by default it will load cdif-onvif-manager module on startup.

This repo is only tested with node v0.10.x on Ubuntu. With other node.js versions the cdif-ble-manager module probably won't work, and if the above npm install command failed, you may need to manually install sqlite3 and bcrypt dependencies.

BTW, the IoT part of this open source project is no longer maintained for now and as you see it is only in experimental stage. We are building a cloud API management service with cdif framework: http://apemesh.com  If you are interested to integrate this project in your production environment, please contact us on our site. Thanks.
